### PR TITLE
Ghost version: v5 admin API works

### PR DESCRIPTION
**Pull request by cpuwolf**
tested on Ghost version: v5.2.3

### CODE REVIEW

**Comment by rycus86** [comment]
Thanks for this!
I'll merge this now but won't be able to release it for a week or so.
I'll try have a look at cutting a PyPI release this weekend.

**Comment by rycus86** [comment]
Hi @cpuwolf 

I just tried looking at this, and can't seem to be able to run tests (with `nose2 -v`) against the latest 5.2 Ghost docker image:
```
======================================================================
ERROR: test_publish (test_posts.PostTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vadam/dev/rycus86/ghost-client/tests/unittest_helper.py", line 14, in setUp
    self.ghost = self._setup_client()
  File "/Users/vadam/dev/rycus86/ghost-client/tests/test_posts.py", line 11, in _setup_client
    return self.new_logged_in_client()
  File "/Users/vadam/dev/rycus86/ghost-client/tests/unittest_helper.py", line 43, in new_logged_in_client
    client = self.new_client(version=version)
  File "/Users/vadam/dev/rycus86/ghost-client/tests/unittest_helper.py", line 38, in new_client
    return Ghost.from_sqlite(
  File "/Users/vadam/dev/rycus86/ghost-client/ghost_client/api.py", line 150, in from_sqlite
    row = connection.execute(
sqlite3.OperationalError: no such table: clients
```

Can you tell me how have you tested it so I could adapt the test cases?

**Comment by cpuwolf** [comment]
@rycus86 ok. I didn't revise the test suits accordingly.

but the above commit in README.md do includes my test case example

**Comment by rycus86** [comment]
Right, so now it needs an API key instead of a username/password, if I read it correctly?
Any chance you could look at getting tests working against a fresh Ghost container?
If not that's fine, but I might not get to release this to PyPI as is, not sure if that's an issue for you.

**Pull request merged**
